#!/bin/bash
# Quick-start guide for Finley YNAB integration

echo "═══════════════════════════════════════════════════════════════════"
echo "  Finley YNAB Financial Intelligence — Quick Start"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✓ YNAB token: SET"
echo "✓ Initial sync: COMPLETE"
echo "✓ Database: ~/.kiro/finley.db"
echo "✓ Config: ~/.kiro/finley_config.json"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  What's Ready"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Finley is now fully integrated into Kiro. You can:"
echo ""
echo "  1. Talk to Finley in your voice loop:"
echo "     → 'Hey Finley, how much did I spend on groceries?'"
echo "     → 'Finley, am I on budget this month?'"
echo "     → 'Show me my spending trend for the last 3 months'"
echo ""
echo "  2. Finley gets real data from YNAB:"
echo "     • Spending by category or merchant"
echo "     • Budget health (vs actual, overspent, runway)"
echo "     • Account balances & net worth"
echo "     • Upcoming bills"
echo "     • Income vs expenses"
echo ""
echo "  3. Finley proactively alerts you:"
echo "     • Budget overspending warnings"
echo "     • Budget runway (<7 days)"
echo "     • Large transactions (>$100)"
echo "     • Spending velocity changes"
echo "     • Positive reinforcement (under budget wins)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Data Sync"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Background daemon:"
echo "  • Runs every 30 minutes (configurable)"
echo "  • Uses delta sync — ~4 API calls per cycle"
echo "  • Generates proactive insights after each sync"
echo "  • Starts automatically when Kiro boots"
echo ""
echo "Manual sync (for testing):"
echo "  conda run -n kiro_asr python -m finley.sync"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Configuration"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Edit ~/.kiro/finley_config.json to:"
echo "  • sync_interval_minutes: Change sync frequency"
echo "  • category_aliases: Add your own category shortcuts"
echo "  • monthly_income_estimate: For budget-to-income ratios"
echo ""
echo "Examples of category aliases (already set):"
echo "  → 'weed' = Cannabis"
echo "  → 'takeout' = Dining Out"
echo "  → 'grocery' = Groceries"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Next Steps"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Start Kiro voice loop:"
echo "  python kiro.py"
echo ""
echo "Then try:"
echo "  'Hey Finley, what are my account balances?'"
echo "  'Finley, where am I overspent?'"
echo "  'Show me my biggest purchases this week'"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
