#!/usr/bin/env python3
"""
ambient/briefing.py — Briefing Composer for the Ambient Intelligence Layer.

Assembles synthesized, prioritized briefings from unsurfaced insights.
Not a simple concatenation — an LLM-driven synthesis step that composes
a unified briefing in Kiro's voice with persona-specific segments.

Briefing types: morning, evening, commute, on_demand, alert.

Kiro's briefing voice: warm, direct, efficient. Like a trusted chief of
staff who respects Tim's time and knows what matters.

Usage:
    python -m ambient.briefing                    # Run as scheduled service
    python -m ambient.briefing --type morning     # Compose specific briefing
    python -m ambient.briefing --type on_demand   # On-demand "catch me up"
"""

from __future__ import annotations

import argparse
import json
import logging
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from ambient.db import AmbientDB
from ambient.llm import AmbientLLM
from ambient.worker import BaseWorker

logger = logging.getLogger("ambient.briefing")

# ── Briefing type configuration ─────────────────────────────────────────────

BRIEFING_CONFIG = {
    "morning": {
        "max_insights": 7,
        "tone": "Calm overview of the day ahead. What happened overnight, what's coming today.",
        "max_words": 400,  # ~2.5 minutes spoken at 150 wpm
        "greeting": "Morning, Tim.",
    },
    "evening": {
        "max_insights": 5,
        "tone": "Reflective. How the day went, what to think about, anything to prep for tomorrow.",
        "max_words": 300,  # ~2 minutes
        "greeting": "Hey Tim, quick evening note.",
    },
    "commute": {
        "max_insights": 5,
        "tone": "Concise, audio-optimized. Designed for the walk or transit to work.",
        "max_words": 250,  # ~1.5 minutes
        "greeting": "Hey Tim, few things on the way in.",
    },
    "on_demand": {
        "max_insights": 15,
        "tone": "Comprehensive. Everything unsurfaced, prioritized. Tim asked for this.",
        "max_words": 600,  # ~4 minutes
        "greeting": "Alright, here's what you've missed.",
    },
    "alert": {
        "max_insights": 1,
        "tone": "Immediate, urgent. Something Tim needs to know right now.",
        "max_words": 100,
        "greeting": "Tim, heads up —",
    },
}

BRIEFING_SYSTEM_PROMPT = """You are Kiro, Tim's AI personal assistant. You are composing a {briefing_type} briefing.

Your voice: warm, direct, efficient. Not robotic, not chatty. Like a trusted chief of staff who respects Tim's time and knows what matters.

Tim's personas you may reference:
- Jack: Master grower (cannabis cultivation, grow tent)
- Finley: Financial advisor (budgets, YNAB)
- Ops: Operations and staff management
- Sage: Cannabis product knowledge
- Coach: Health and fitness
- Chef: Cooking and nutrition

Rules:
- Open with the most important or time-sensitive item
- Group related insights naturally (don't rigidly go persona-by-persona)
- Use each persona's voice when delivering their specific insight
- Bridge cross-persona connections explicitly ("Finley noticed X, and since your calendar shows Y...")
- Close with anything Tim should keep in mind or prep for
- Stay under {max_words} words (this will be spoken aloud at ~150 words per minute)
- Do NOT pad with filler or pleasantries beyond the opening greeting
- Do NOT repeat information Tim has already been told
- If there are more insights than the cap ({max_insights}), triage — include the most important ones
- Be natural. Tim is hearing this spoken aloud."""

BRIEFING_USER_TEMPLATE = """Current time: {timestamp}

{calendar_section}

The following insights have been generated by your personas since the last briefing:

{insights_grouped}

Compose the {briefing_type} briefing. Open with: "{greeting}"
"""


class BriefingComposer:
    """
    Composes briefings from unsurfaced insights.

    Can be used both as a scheduled worker (via BriefingWorker) and
    as a callable from the main Kiro pipeline (for on-demand briefings).
    """

    def __init__(self, db: Optional[AmbientDB] = None, llm: Optional[AmbientLLM] = None) -> None:
        self._db = db or AmbientDB()
        if llm is None:
            model_routing = self._db.get_config("model_routing", {})
            self._llm = AmbientLLM(model_routing=model_routing if isinstance(model_routing, dict) else {})
        else:
            self._llm = llm

    def _get_calendar_context(self) -> str:
        """Get today's calendar events for briefing context."""
        events = self._db.get_events_in_window(days=1, source="gcal", processed_only=False)
        if not events:
            return "Tim's schedule today: No calendar events visible."

        today_events = []
        today = datetime.now(timezone.utc).date()
        for e in events:
            meta = e.get("metadata", {})
            start = meta.get("start", "")
            summary = meta.get("summary", "")
            location = meta.get("location", "")

            # Check if event is today
            if start and str(today) in start:
                today_events.append(f"- {start[11:16] if 'T' in start else 'All day'}: {summary}" +
                                    (f" ({location})" if location else ""))

        if today_events:
            return "Tim's schedule today:\n" + "\n".join(today_events)
        return "Tim's schedule today: Clear — no events scheduled."

    def _group_insights(self, insights: List[Dict]) -> str:
        """Group insights by persona for the briefing prompt."""
        grouped: Dict[str, List[str]] = defaultdict(list)

        for insight in insights:
            persona = insight.get("persona") or "Kiro"
            persona_name = persona.capitalize()
            priority = insight.get("priority", 5)
            insight_type = insight.get("insight_type", "")

            entry = f"[Priority {priority}, {insight_type}] {insight.get('summary', '')}"
            if insight.get("detail"):
                entry += f"\n  Detail: {insight['detail']}"

            grouped[persona_name].append(entry)

        sections = []
        for persona, items in sorted(grouped.items()):
            sections.append(f"### {persona}\n" + "\n".join(f"  {i+1}. {item}" for i, item in enumerate(items)))

        return "\n\n".join(sections)

    def compose(
        self,
        briefing_type: str = "morning",
        force: bool = False,
    ) -> Optional[Dict[str, Any]]:
        """
        Compose a briefing of the given type.

        Returns:
            Dict with 'briefing_id', 'text', 'insight_count', 'type'
            or None if no insights to surface.
        """
        config = BRIEFING_CONFIG.get(briefing_type, BRIEFING_CONFIG["morning"])
        max_insights = config["max_insights"]

        # Get max insights from DB config if set
        db_max = self._db.get_config("max_insights_per_briefing")
        if isinstance(db_max, int):
            max_insights = min(max_insights, db_max)

        # Get priority threshold
        priority_threshold = self._db.get_config("priority_threshold", 6)
        if not isinstance(priority_threshold, int):
            priority_threshold = int(priority_threshold)

        # For alerts, only look at priority 1-2
        if briefing_type == "alert":
            priority_threshold = 2

        # Fetch unsurfaced insights
        insights = self._db.get_unsurfaced_insights(
            max_priority=priority_threshold,
            limit=max_insights * 2,  # Fetch extra for triaging
        )

        if not insights and not force:
            logger.debug("No unsurfaced insights for %s briefing", briefing_type)
            return None

        if not insights:
            insights = []

        # Sort by priority (most important first)
        insights.sort(key=lambda i: (i.get("priority", 5), i.get("created_at", "")))

        # Cap at max
        selected = insights[:max_insights]

        if not selected and not force:
            return None

        # Build the prompt
        calendar_section = self._get_calendar_context()
        insights_grouped = self._group_insights(selected) if selected else "No new insights since the last briefing."

        system_prompt = BRIEFING_SYSTEM_PROMPT.format(
            briefing_type=briefing_type,
            max_words=config["max_words"],
            max_insights=max_insights,
        )

        user_prompt = BRIEFING_USER_TEMPLATE.format(
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            calendar_section=calendar_section,
            insights_grouped=insights_grouped,
            briefing_type=briefing_type,
            greeting=config["greeting"],
        )

        # Compose via LLM
        try:
            briefing_text = self._llm.complete(
                task="briefing",
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                temperature=0.4,
                max_tokens=config["max_words"] * 2,  # Token buffer
            )
        except Exception as e:
            logger.error("Briefing composition failed: %s", e)
            return None

        # Build persona segments for tracking
        persona_segments = defaultdict(list)
        for insight in selected:
            persona = insight.get("persona") or "kiro"
            persona_segments[persona].append(insight.get("summary", ""))

        # Store the briefing and mark insights as surfaced
        insight_ids = [i["id"] for i in selected]
        briefing_id = self._db.insert_briefing(
            briefing_type=briefing_type,
            insight_ids=insight_ids,
            briefing_text=briefing_text,
            persona_segments=dict(persona_segments),
            delivery_method="voice",
        )

        logger.info("Composed %s briefing #%d with %d insights",
                     briefing_type, briefing_id, len(selected))

        return {
            "briefing_id": briefing_id,
            "text": briefing_text,
            "insight_count": len(selected),
            "type": briefing_type,
            "insight_ids": insight_ids,
        }

    def get_on_demand(self) -> Optional[Dict[str, Any]]:
        """Compose an on-demand 'catch me up' briefing."""
        return self.compose(briefing_type="on_demand", force=True)

    def check_alerts(self) -> Optional[Dict[str, Any]]:
        """Check for critical insights (priority 1-2) that need immediate alerting."""
        return self.compose(briefing_type="alert")


class BriefingWorker(BaseWorker):
    """
    Scheduled briefing composer. Checks if it's time for a briefing
    and composes one if there are unsurfaced insights.
    """

    worker_name = "briefing_composer"
    default_interval_seconds = 300  # Check every 5 minutes

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self._composer: BriefingComposer | None = None
        self._last_morning: Optional[str] = None
        self._last_evening: Optional[str] = None

    def setup(self) -> None:
        """Initialize the briefing composer."""
        model_routing = self.db.get_config("model_routing", {})
        llm = AmbientLLM(model_routing=model_routing if isinstance(model_routing, dict) else {})
        self._composer = BriefingComposer(db=self.db, llm=llm)
        self.audit_log("INFO", "Briefing Composer worker initialized")

    def process(self) -> None:
        """Check schedule and compose briefings as needed."""
        now = datetime.now()
        current_time = now.strftime("%H:%M")
        today = now.strftime("%Y-%m-%d")

        # Get schedule from config
        schedule = self.db.get_config("briefing_schedule", {
            "morning": "07:00",
            "evening": "21:00",
        })
        if not isinstance(schedule, dict):
            schedule = {"morning": "07:00", "evening": "21:00"}

        # ── Morning briefing ──
        morning_time = schedule.get("morning", "07:00")
        if (
            morning_time != "disabled"
            and current_time >= morning_time
            and self._last_morning != today
        ):
            result = self._composer.compose(briefing_type="morning")
            if result:
                self._last_morning = today
                self.audit_log("INFO", f"Morning briefing composed: {result['insight_count']} insights", {
                    "briefing_id": result["briefing_id"],
                })
            else:
                self._last_morning = today  # Don't retry if nothing to say

        # ── Evening briefing ──
        evening_time = schedule.get("evening", "21:00")
        if (
            evening_time != "disabled"
            and current_time >= evening_time
            and self._last_evening != today
        ):
            result = self._composer.compose(briefing_type="evening")
            if result:
                self._last_evening = today
                self.audit_log("INFO", f"Evening briefing composed: {result['insight_count']} insights", {
                    "briefing_id": result["briefing_id"],
                })
            else:
                self._last_evening = today

        # ── Alert check (always) ──
        alert = self._composer.check_alerts()
        if alert:
            self.audit_log("ALERT", f"ALERT briefing triggered: {alert['text'][:100]}...", {
                "briefing_id": alert["briefing_id"],
            })
            # TODO: Wire into voice pipeline for immediate delivery


def main():
    import sys

    parser = argparse.ArgumentParser(description="Kiro Briefing Composer")
    parser.add_argument("--type", choices=["morning", "evening", "commute", "on_demand", "alert"],
                        help="Compose a specific briefing type immediately")
    args = parser.parse_args()

    if args.type:
        # One-shot: compose a specific briefing
        logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
        composer = BriefingComposer()
        result = composer.compose(briefing_type=args.type, force=(args.type == "on_demand"))
        if result:
            print(f"\n{'='*60}")
            print(f"Briefing #{result['briefing_id']} ({result['type']})")
            print(f"Insights: {result['insight_count']}")
            print(f"{'='*60}\n")
            print(result["text"])
        else:
            print("No insights to surface. All quiet.")
    else:
        # Run as scheduled worker
        worker = BriefingWorker()
        worker.run()


if __name__ == "__main__":
    main()
